Resources:
  CmsApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
      - Key: CMS
        Value: CmsApiStack
      TemplateURL: https://s3-ap-southeast-1.amazonaws.com/gabriel-serverless-cms/templates/01-create_rest_api.yaml
  CmsLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
      - Key: CMS
        Value: CmsLambdaStack
      TemplateURL: https://s3-ap-southeast-1.amazonaws.com/gabriel-serverless-cms/templates/02-create_lambda_function.yaml
    DependsOn:
      - CmsApiStack  
  ApiPostMethodStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
      - Key: CMS
        Value: ApiPostMethodStack
      TemplateURL: https://s3-ap-southeast-1.amazonaws.com/gabriel-serverless-cms/templates/03-api_add_post_method.yaml
    DependsOn:
      - CmsLambdaStack
  ApiOptionsMethodStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
      - Key: CMS
        Value: ApiOptionsMethodStack
      TemplateURL: https://s3-ap-southeast-1.amazonaws.com/gabriel-serverless-cms/templates/04-api_add_options_method.yaml
    DependsOn:
      - CmsLambdaStack
  DeployApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
      - Key: CMS
        Value: DeployApiStack
      TemplateURL: https://s3-ap-southeast-1.amazonaws.com/gabriel-serverless-cms/templates/05-deploy_api.yaml
    DependsOn:
      - ApiPostMethodStack
      - ApiOptionsMethodStack