Resources:
  CmsApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
      - Key: CMS
        Value: CmsApiStack
      TemplateURL: https://s3-ap-southeast-1.amazonaws.com/gabriel-serverless-cms/templates/01-create_rest_api.yaml
  CmsLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
      - Key: CMS
        Value: CmsLambdaStack
      TemplateURL: https://s3-ap-southeast-1.amazonaws.com/gabriel-serverless-cms/templates/02-create_lambda_function.yaml
    DependsOn:
      - CmsApiStack  
  ApiPostMethodStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
      - Key: CMS
        Value: ApiPostMethodStack
      TemplateURL: https://s3-ap-southeast-1.amazonaws.com/gabriel-serverless-cms/templates/03-api_add_post_method.yaml
    DependsOn:
      - CmsLambdaStack
  ApiOptionsMethodStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
      - Key: CMS
        Value: ApiOptionsMethodStack
      TemplateURL: https://s3-ap-southeast-1.amazonaws.com/gabriel-serverless-cms/templates/04-api_add_options_method.yaml
    DependsOn:
      - CmsLambdaStack
  DeployApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
      - Key: CMS
        Value: DeployApiStack
      TemplateURL: https://s3-ap-southeast-1.amazonaws.com/gabriel-serverless-cms/templates/05-deploy_api.yaml
    DependsOn:
      - ApiPostMethodStack
      - ApiOptionsMethodStack
  CreateBucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
      - Key: CMS
        Value: CreateBucketStack
      TemplateURL: https://s3-ap-southeast-1.amazonaws.com/gabriel-serverless-cms/templates/06-create_bucket.yaml
  CreateCDNStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
      - Key: CMS
        Value: CreateCDNStack
      TemplateURL: https://s3-ap-southeast-1.amazonaws.com/gabriel-serverless-cms/templates/07-create_cloudfront_distribution.yaml
    DependsOn:
      - CreateBucketStack
  CreateBlogTableStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
      - Key: CMS
        Value: CreateBlogTableStack
      TemplateURL: https://s3-ap-southeast-1.amazonaws.com/gabriel-serverless-cms/templates/08-create_blog_table.yaml
  CreatePageTableStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
      - Key: CMS
        Value: CreatePageTableStack
      TemplateURL: https://s3-ap-southeast-1.amazonaws.com/gabriel-serverless-cms/templates/09-create_page_table.yaml
  CreateTokenTableStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
      - Key: CMS
        Value: CreateTokenTableStack
      TemplateURL: https://s3-ap-southeast-1.amazonaws.com/gabriel-serverless-cms/templates/10-create_token_table.yaml
  CreateRoleTableStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
      - Key: CMS
        Value: CreateRoleTableStack
      TemplateURL: https://s3-ap-southeast-1.amazonaws.com/gabriel-serverless-cms/templates/11-create_role_table.yaml
  CreateUserTableStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
      - Key: CMS
        Value: CreateUserTableStack
      TemplateURL: https://s3-ap-southeast-1.amazonaws.com/gabriel-serverless-cms/templates/12-create_user_table.yaml