Resources:   
   PostMethod: 
       Type: "AWS::ApiGateway::Method"
       Properties: 
          RestApiId: !ImportValue ApiId
          ResourceId: !ImportValue RootResourceId
          HttpMethod: "POST"
          RequestParameters:
              method.request.header.Cookie: False
          AuthorizationType: "NONE"
          Integration: 
             Type: "AWS"
             PassthroughBehavior: "NEVER"
             IntegrationHttpMethod: "POST"
             Uri: !Sub  
                - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CmsLambdaArn}/invocations"
                - {CmsLambdaArn: !ImportValue CmsLambdaArn}
             RequestTemplates:
               "application/json": "{'application/json': '#if($input.params('Cookie') && $input.params('Cookie') != '') {'body': $input.body, 'token': '$input.params('Cookie')'}#else{'body': $input.body}#end'}"
             
             IntegrationResponses: 
                - ResponseParameters:
                    method.response.header.Set-Cookie: "integration.response.body.Set-Cookie"
                    method.response.header.Access-Control-Allow-Credentials: "'true'"
                    method.response.header.Access-Control-Allow-Origin:
                      !Sub "'https://s3-${AWS::Region}.amazonaws.com'" 
                  ResponseTemplates:
                    application/json: "$input.body"
                  StatusCode: "200"
                - ResponseParameters:
                    method.response.header.Access-Control-Allow-Credentials: "'true'"
                    method.response.header.Access-Control-Allow-Origin:
                      !Sub  "'https://s3-${AWS::Region}.amazonaws.com'"           
                  ResponseTemplates:
                    application/json: "$input.path('$.errorMessage')"
                  SelectionPattern: ".*'status': 400.*"
                  StatusCode: "400"         
          MethodResponses:
                - ResponseModels:
                    application/json: Empty
                  ResponseParameters:
                    method.response.header.Set-Cookie: False
                    method.response.header.Access-Control-Allow-Credentials: False
                    method.response.header.Access-Control-Allow-Origin: False
                  StatusCode: "200"
                - ResponseModels:
                    application/json: Empty
                  ResponseParameters:
                    method.response.header.Access-Control-Allow-Credentials: False
                    method.response.header.Access-Control-Allow-Origin: False
                  StatusCode: "400"
   