Resources:     
   OptionsMethod: 
    Type: "AWS::ApiGateway::Method"
    Properties: 
     RestApiId: !ImportValue ApiId
     ResourceId: !ImportValue RootResourceId
     HttpMethod: "OPTIONS"
     AuthorizationType: "NONE"
     Integration: 
       Type: "MOCK"
       RequestTemplates:
         "application/json": "{'statusCode': 200}"
       IntegrationResponses: 
          - ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Cookie,Accept,Access-Control-Allow-Origin'" 
              method.response.header.Access-Control-Allow-Credentials: "'true'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin:
               !Sub "'https://s3-${AWS::Region}.amazonaws.com'"             
            ResponseTemplates:
              application/json: ""
            StatusCode: "200"        
     MethodResponses:
       - ResponseModels:
           application/json: Empty
         ResponseParameters:
           method.response.header.Set-Cookie: False
           method.response.header.Access-Control-Allow-Credentials: False
           method.response.header.Access-Control-Allow-Origin: False
           method.response.header.Access-Control-Allow-Methods: False
           method.response.header.Access-Control-Allow-Headers: False
         StatusCode: "200"  