Resources:
   CMSApi:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Description: "test Api"
      Name: "CMS-opeartion-api"           
Outputs:
   ApiId:
     Description: API ID
     Value: !Ref CMSApi
   ApiUrl:
     Description: API Url
     Value: 
       !Sub | 
         - https://${!apiId}.execute-api.${AWS::Region}.amazonaws.com/prod # for non presudo variable or custom variable use #${!varaibleName}
         - { apiId: !Ref CMSApi }
   ApiPermissionsUri:
     Description: API Permissions Uri
     Value: 
       !Sub |
        - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${!apiId}/*/POST/
        - { apiId:  !Ref CMSApi }
    
      